name: formdator
description: A formidable set of form validators that can be selected and grouped into various combinations. Each validator is an immutable object that can be easily extended through composition - Decorator Pattern.
version: 0.2.1
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/formdator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cpf_cnpj_validator: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
